export const Urls: any = {
  login: 'login',
  downloadWorklog: 'w/downloadWorklog',
  type1Count: 'w/type1Count',
  type2Count: 'w/type2Count',
  update: 'w/update',
  updateCheck: 'w/updateCheck',
  workLog: 'w/workLog',
  workLogFromContent: 'w/workLogFromContent',
  workLogFromDate: 'w/workLogFromDate',
  workLogFromMonth: 'w/workLogFromMonth',
  workLogFromType: 'w/workLogFromType',
  workLogFromWeek: 'w/workLogFromWeek',
  workType: 'w/workType',
  workType1: 'w/workType1',
  workType2: 'w/workType2',
}
